#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
                ref class TextBox;
            }
        }
    }
}

namespace Calculator
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Button^ exit_imagebutton;
        private: ::Windows::UI::Xaml::Controls::Button^ add_button;
        private: ::Windows::UI::Xaml::Controls::Button^ sub_button;
        private: ::Windows::UI::Xaml::Controls::Button^ mul_button;
        private: ::Windows::UI::Xaml::Controls::Button^ div_button;
        private: ::Windows::UI::Xaml::Controls::TextBox^ result_textbox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ second_operand_textbox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ first_operand_textbox;
        private: ::Windows::UI::Xaml::Controls::Button^ add_imagebutton;
        private: ::Windows::UI::Xaml::Controls::Button^ sub_imagebutton;
        private: ::Windows::UI::Xaml::Controls::Button^ mul_imagebutton;
        private: ::Windows::UI::Xaml::Controls::Button^ div_imagebutton;
    };
}

